### ISSUE TITLE
The "quake.feed" action is missing in the windows system

### ISSUE THREAD

**Issue by HuangDayu** [phodal/quake#15]
### Describe the bug

The "quake.feed" file is missing in the windows system

### Steps to reproduce (please include code)

```shell
quake-windows.exe cmd -i "quake.feed"
```

### Environment
- cargo 1.57.0 (b2e52d7ca 2021-10-21)
- rustc 1.57.0 (f1edd0429 2021-11-29)
- OS: Windows 10

**Comment by phodal** [comment]
`quake.feed` is a action, not a file

**Comment by phodal** [comment]
execute `quake init` first ,will not have this issue.
