### ISSUE TITLE
bug: setup error

### ISSUE THREAD

**Issue by boqingren** [phodal/quake#19]
### Describe the bug
**I run "quake server" in terminal, then I got an error:**

![image](https://user-images.githubusercontent.com/33900216/145706912-b11a661b-6a16-4027-9e39-06965e5664b8.png)

### Steps to reproduce (please include code)
1. quake init.
2. quake cmd -i "todo.add: hello, world".
3. quake server.
```bssh
tree -C -L 2 .             
.
├── entries-define.yaml
└── todo
    ├── 0001-hello-world.md
    ├── entries.csv
    └── entry-node-info.yaml
```

### Environment
- coco version: cargo 1.57.0 (b2e52d7ca 2021-10-21)
- Rust version: rustc 1.57.0 (f1edd0429 2021-11-29)
- OS: [e.g. OSX 10.13.4, Windows 10]: macOS Big Sur 11.6.0

**Comment by phodal** [comment]
hi, try

1. download `web.zip` from [https://github.com/phodal/quake/releases](https://github.com/phodal/quake/releases)
2. unzip to `web` directory
3. try `quake server` again

**Comment by Eliot00** [comment]
I will work on this issue
