### ISSUE TITLE
discuss: last modified time

### ISSUE THREAD

**Issue by Eliot00** [phodal/quake#3]
目前编辑entry并不会自动更新updatedAt，这个功能是否应该内置？已经存在一些编辑器插件如[vscode-front-matter](https://github.com/estruyf/vscode-front-matter)可以做这件事

**Comment by phodal** [comment]
从实现的角度来看的话，调用三方的编辑器的时候，应该是实现不了的。

但是，如果使用 WebApp 编辑的话，是已经内置了这个功能的：https://github.com/phodal/quake/blob/1ac598152786b68d49990484eb4c4e0c71093640/src/action/entry_usecases.rs#L92
