### ISSUE TITLE
Bug: entry_watcher throw `no such file` error while create a new entry

### ISSUE THREAD

**Issue by Eliot00** [phodal/quake#40]
### Steps to reproduce (please include code)

1. `mkdir quake_test && cd quake_test`
2. run `quake init -d`
3. run meilisearch
3. run `quake server -w`
4. open webapp and create a new entry by action `todo.add: hello`
5. edit and click save button
6. open console see the log: `ERROR quake::helper::entry_watcher: watch error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

### Environment
- quake version: git hash 20ec718
- Rust version: 1.57
- OS: macos 11.2.1

**Comment by phodal** [comment]
can't reproduce
