### ISSUE TITLE
帮忙看下quake server 出现错误

### ISSUE THREAD

**Issue by xp12047** [phodal/quake#56]
###  不知道为什么quake server不能正常工作
![mmexport1663245168268](https://user-images.githubusercontent.com/56335408/190406154-8052ed7b-00ee-46f0-9091-c71d3a665ee3.png)

### Environment  :windows 11 64
- quake version: 
- Rust version: rustc 1.62.1
- OS: [e.g. OSX 10.13.4, Windows 10] windows11

**Comment by phodal** [comment]
没有找到 web 目录，需要去 Desktop/aa 目录试试

**Comment by xp12047** [comment]
> 没有找到网络目录，需要去桌面/aa目录尝试

![mmexport1663248794794](https://user-images.githubusercontent.com/56335408/190417433-141969d9-d9f3-425f-a406-3d121b68f905.png)
也不行呢，帮忙看下我改了自动生成的yml文件

**Comment by phodal** [comment]
好像漏了第一步：

1. download web from release

**Comment by xp12047** [comment]
> 漏了前期：
> 
> 1. 从发布下载网页

那该怎么？

**Comment by phodal** [comment]
补上下载就好了

**Comment by xp12047** [comment]
> 补上下载就好了

额，是在" "里面补download web from release？

**Comment by phodal** [comment]
从这里下载 https://github.com/phodal/quake/releases/tag/v0.5.1 ，然后解压到 .quake.yml 同级

**Comment by xp12047** [comment]
> 从这里下载https://github.com/phodal/quake/releases/tag/v0.5.1，然后解压到 .quake.yml 同级

谢谢

**Comment by xp12047** [comment]
> 从这里下载https://github.com/phodal/quake/releases/tag/v0.5.1，然后解压到 .quake.yml 同级

我还想问个问题，我进入quake tui后怎么退出来？q，exit，都不行 保存又是？

**Comment by xp12047** [comment]
> > 从这里下载[https://github.com/phodal/quake/releases/tag/v0.5.1，然后解压到](https://github.com/phodal/quake/releases/tag/v0.5.1%EF%BC%8C%E7%84%B6%E5%90%8E%E8%A7%A3%E5%8E%8B%E5%88%B0).quake.yml同级
> 
> 谢谢

谢谢，好了😁
